/**
 * This file will be auto-generated by openapi-typescript.
 * To generate it, run the API server first, then run:
 * pnpm --filter @treeproai/sdk-js generate
 */

export type paths = Record<string, any>;
export type webhooks = Record<string, any>;
export type components = Record<string, any>;
export type external = Record<string, any>;
export type operations = Record<string, any>;