/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/quotes/analyze": {
    /** @summary Analyze images and compose a price range + rationale */
    post: {
      requestBody?: {
        content: {
          "multipart/form-data": {
            /** Format: uuid */
            propertyId?: string;
            images?: string[];
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              quoteId?: string;
              priceMin?: number;
              priceMax?: number;
              hazards?: string[];
              rationale?: string;
            };
          };
        };
      };
    };
  };
  "/api/schedule/optimize": {
    /** @summary Optimize crews & routes (VRP) */
    post: {
      responses: {
        /** @description OK */
        200: never;
      };
    };
  };
  "/api/nws/ingest": {
    /** @summary Ingest an NWS alert payload for the service area */
    post: {
      responses: {
        /** @description Accepted */
        202: never;
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: Record<string, never>;
  responses: Record<string, never>;
  parameters: Record<string, never>;
  requestBodies: Record<string, never>;
  headers: Record<string, never>;
  pathItems: Record<string, never>;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;