# treeproai/.github/workflows/ci.yml
# This workflow builds and pushes Docker images for all services to the GitHub Container Registry.

name: CI/CD - Build and Push Docker Images

on:
  push:
    branches:
      - "main"

env:
  REGISTRY: ghcr.io
  # github.repository as <owner>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push 'web' image
        uses: docker/build-push-action@v5
        with:
          context: ./treeproai
          file: ./treeproai/infra/docker/web.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push 'api' image
        uses: docker/build-push-action@v5
        with:
          context: ./treeproai
          file: ./treeproai/infra/docker/api.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push 'ai-vision' image
        uses: docker/build-push-action@v5
        with:
          context: ./treeproai
          file: ./treeproai/infra/docker/ai-vision.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/ai-vision:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push 'ai-pricing' image
        uses: docker/build-push-action@v5
        with:
          context: ./treeproai
          file: ./treeproai/infra/docker/ai-pricing.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/ai-pricing:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push 'ai-tabular' image
        uses: docker/build-push-action@v5
        with:
          context: ./treeproai
          file: ./treeproai/infra/docker/ai-tabular.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/ai-tabular:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push 'forecast' image
        uses: docker/build-push-action@v5
        with:
          context: ./treeproai
          file: ./treeproai/infra/docker/forecast.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/forecast:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push 'routing' image
        uses: docker/build-push-action@v5
        with:
          context: ./treeproai
          file: ./treeproai/infra/docker/routing.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/routing:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push 'ocr' image
        uses: docker/build-push-action@v5
        with:
          context: ./treeproai
          file: ./treeproai/infra/docker/ocr.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/ocr:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push 'speech' image
        uses: docker/build-push-action@v5
        with:
          context: ./treeproai
          file: ./treeproai/infra/docker/speech.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/speech:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max