// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bkqzewwmgrxayzzkrmgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrcXpld3dtZ3J4YXl6emtybWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExMDIyMjksImV4cCI6MjA3NjY3ODIyOX0.8JkO3wxY7oLVi88giLkfbcDR9wPuJdf-CEHCi_lyI7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);